#!/usr/bin/env python3
"""Build Markdown pages and dated posts into the repository root."""

from datetime import date
from html import escape
from pathlib import Path
from string import Template
import re
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parent.parent
MARKER = "<!-- Generated by scripts/build.py; edit content/ or templates/ instead. -->"


def markdown(source):
    return subprocess.run(
        ["markdown"], input=source, text=True, encoding="utf-8",
        capture_output=True, check=True,
    ).stdout.strip()


def build():
    if not shutil.which("markdown"):
        raise ValueError("Install Discount (the 'markdown' command), then run make again.")

    template = Template((ROOT / "templates/page.html").read_text(encoding="utf-8"))
    if MARKER not in template.template:
        raise ValueError("Keep the generated-file comment in templates/page.html.")

    outputs = {}
    has_now = (ROOT / "content/now.md").is_file()
    navigation = '<a href="index.html">home</a>'
    if has_now:
        navigation += ' · <a href="now/">now</a>'

    def page(filename, title, body):
        base = "../" * (len(Path(filename).parts) - 1) or "./"
        outputs[filename] = template.substitute(
            title=escape(title), body=body, base=base, navigation=navigation,
        )

    posts = []
    for path in sorted((ROOT / "content/posts").glob("*.md"), reverse=True):
        match = re.fullmatch(r"(\d{4}-\d{2}-\d{2})-[a-z0-9]+(?:-[a-z0-9]+)*", path.stem)
        if not match:
            raise ValueError(f"{path.name}: use YYYY-MM-DD-post-slug.md")
        published = date.fromisoformat(match[1]).isoformat()
        source = path.read_text(encoding="utf-8")
        first_line = source.splitlines()[0] if source else ""
        if not first_line.startswith("# ") or not first_line[2:].strip():
            raise ValueError(f"{path.name}: start with '# Your post title'")
        title = first_line[2:].strip()
        filename = path.with_suffix(".html").name
        body = f'<p><time datetime="{published}">{published}</time></p>\n{markdown(source)}'
        page(filename, f"{title} — Felix Angell", f"<article>\n{body}\n</article>")
        posts.append(f'<li><time datetime="{published}">{published}</time> · '
                     f'<a href="{filename}">{escape(title)}</a></li>')

    for name, title in (("index", "Felix Angell"), ("now", "Now — Felix Angell")):
        if name == "now" and not has_now:
            continue
        body = markdown((ROOT / f"content/{name}.md").read_text(encoding="utf-8"))
        if name == "index" and posts:
            body += '\n<h2>Posts</h2>\n<ul class="posts">\n' + "\n".join(posts) + "\n</ul>"
        page(f"{name}.html", title, body)
        if name == "now":
            page("now/index.html", title, body)

    # Render everything successfully before changing the published files.
    for filename, html in outputs.items():
        target = ROOT / filename
        target.parent.mkdir(parents=True, exist_ok=True)
        if not target.exists() or target.read_text(encoding="utf-8") != html:
            target.write_text(html, encoding="utf-8")

    # Remove only our own obsolete output after a page or post is deleted.
    for path in [*ROOT.glob("*.html"), ROOT / "now/index.html"]:
        filename = path.relative_to(ROOT).as_posix()
        if (filename not in outputs and path.is_file()
                and MARKER in path.read_text(encoding="utf-8")):
            path.unlink()
    (ROOT / ".nojekyll").touch()
    print(f"Built {len(outputs)} pages in {ROOT}")


if __name__ == "__main__":
    try:
        build()
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        sys.exit(f"Build failed: {error}")
